stages:
  - build
  - test
#  - release
#  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build-linux:
  image: ubuntu:22.04
  stage: build
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - apt install -qy --no-install-recommends g++ make pip perl libmysqlclient-dev
    - pip install conan cmake
    - ln -s /usr/local/bin/cmake /usr/bin/cmake
  script:
    - conan profile detect --force
    - conan install . --output-folder=build --build=missing
    - cd build
    - cmake .. -DCMAKE_CXX_FLAGS=-isystem\ /usr/include/mysql -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -j`nproc`
  artifacts:
    paths:
      - build/bin

build-docker:
  image: docker:23.0.5
  stage: build
  before_script:
    - docker login -u $VAR_TEST_USER -p $VAR_TEST_PAT $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  

test-linux:
  image: ubuntu:22.04
  stage: test
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - apt install -qy --no-install-recommends mysql-server
    - service mysql restart
  script:
    - mysql -e "CREATE USER 'admin'@'127.0.0.1' IDENTIFIED BY '123456';"
    - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'127.0.0.1';"
    - mysql -e "CREATE DATABASE RealworldTest;"
    - mysql RealworldTest < sql/realworld.sql
    - export REALWORLD_TEST_DB_HOST=127.0.0.1
    - export REALWORLD_TEST_DB_PORT=3306
    - export REALWORLD_TEST_DB_NAME=RealworldTest
    - export REALWORLD_TEST_DB_USER=admin
    - export REALWORLD_TEST_DB_PASSWORD=123456
    - cd build/bin
    - ./Realworld-test

#code_quality:
#  image: ubuntu:22.04
#  stage: test
#  before_script:
#    - apt update -qy
#    - apt upgrade -qy
#    - apt -qy install cppcheck
#  script:
#    - cppcheck --xml --enable=all ./src/ 2> cppcheck_out.xml
#  artifacts:
#    paths:
#      - cppcheck_out.xml

#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
